### ISSUE TITLE
Feature Request: Add the same behaviour for files opened from the file sidebar

### ISSUE THREAD

**Issue by frigvid** [scambier/obsidian-no-dupe-leaves#3]
Currently, this plugin only focuses on already opened tabs if they are opened from a link within the markdown file. It does not do this for files opened from the file sidebar, but I think it'd be a nice addition to have. I don't know if it is using a different function, but I assume so, and it may be prudent to leave it disabled by default? I'm not familiar with the internals of Obsidian, so I can't really speak for how breaking such an addition would be, but I wanted to air the idea at least.

Regardless, thank you for this plugin. It makes the usage of Obsidian more bearable in its current state.

**Comment by scambier** [comment]
I already spent a few hours trying to get this behavior [without success](https://github.com/scambier/obsidian-no-dupe-leaves/issues/1#issuecomment-1232088759). I didn't find a clear path to patch, and decided to stop trying because messing with internal apis without a clear understanding could bring nasty bugs.

I invite you to add your voice to the Obsidian's feature request :) https://forum.obsidian.md/t/ide-style-navigation-tab-reuse-on-link-opening-tab-management/46671/2

**Comment by frigvid** [comment]
I already have :) Let's just hope they change the default behaviour. Thanks for the quick reply and explanation! I'll just close this issue, since there's no need to keep it open.

**Comment by Aivean** [comment]
FYI, the same issue occurs with the "Quick switcher".
